### ISSUE TITLE
Analysis Page

### ISSUE THREAD

**Issue by kescardoso** [kescardoso/datasetbucket#45]
Created a page with a text input form, to analyze datasets from a Kaggle command or url.

The page is not pragmatically functioning, it needs further developments and installation to link the HTML form to the bias auditor app.

Link to the deployed version: https://datasetbucket.herokuapp.com/analyse_data

**Comment by kescardoso** [comment]
Page created, but not programmatically.
Needs function to connect the analysis tool
@sakshigupta265 @eliboss @wyang0216

**Comment by elleanne** [comment]
The branch, connect_front_back, connects the page to the analysis tool.

Added error message to analyse.html page when a report can not be generated.

Connected runTerminalCommands.py to app.py so that when a URL is submitted on analyse.html, it is grabbed by app.py and sent to runTerminalCommands.py and downloaded and analyzed. If a report is generated, it is downloaded as a pdf in the user's browser.
